package com.opsbot.dto;

import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.OffsetDateTime;
import java.util.Map;

/**
 * Structured alert event sent by client via Kafka.
 *
 * This is the canonical event format shared between:
 * - Python client (producer)
 * - Cloud ingestion layer (consumer)
 * - Event Processor (consumer)
 * - RcaService (processor)
 *
 * Versioned in Git for schema evolution tracking.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class AlertEvent {

    /**
     * Unique identifier for this alert event.
     * Generated by client (uuid4) to enable deduplication.
     */
    private String eventId;

    /**
     * Source client identifier (e.g., "prod-server-01", "dev-cluster-us-west").
     * Used for routing, filtering, and observability.
     */
    private String source;

    /**
     * The service/component that triggered the anomaly.
     * Examples: "api-gateway", "postgres-primary", "kafka-broker-1"
     */
    private String service;

    /**
     * Anomaly type detected by rule engine.
     * Examples: "high_cpu", "high_memory", "log_error_spike", "service_unhealthy"
     */
    @JsonProperty("alert_type")
    private String alertType;

    /**
     * Severity level assigned by rule engine.
     * Values: LOW, MEDIUM, HIGH, CRITICAL
     */
    private String severity;

    /**
     * Unix timestamp (millis) when anomaly was first detected on client.
     */
    private Long detectedAtMs;

    /**
     * Structured signals that triggered the alert.
     * Examples:
     * {
     *   "cpu_percent": 92.5,
     *   "memory_percent": 88.3,
     *   "error_count_5m": 150,
     *   "error_rate": 0.05,
     *   "response_time_p99_ms": 2500
     * }
     */
    private Map<String, Object> signals;

    /**
     * Short-form context lines from log/metrics that triggered rule.
     * Truncated to 500 chars total to avoid bloating event size.
     * Examples:
     * [
     *   "ERROR [2026-05-02 10:15:22] Connection pool exhausted",
     *   "ERROR [2026-05-02 10:15:23] Failed to acquire DB connection"
     * ]
     */
    private java.util.List<String> contextLogs;

    /**
     * Fingerprint hash of (source, service, alertType, timestamp_bucket).
     * Used by Event Processor for deduplication within 30s window.
     * Computed by client; allows server-side dedup without recomputing.
     */
    private String fingerprint;

    /**
     * Timestamp when this event was created and serialized.
     * Server uses this for ordering if Kafka reordering occurs.
     */
    @JsonProperty("created_at")
    private OffsetDateTime createdAt;

    /**
     * Optional metadata for debugging/routing.
     * Examples: {"deployment_id": "v1.2.3", "region": "us-west-2"}
     */
    private Map<String, String> metadata;
}

